name:    back
version: "0.0.0"

dependencies:
- base
- yesod-core
- yesod
- persistent-postgresql >= 2.10.1.2
- text >= 1.2.4.0
- monad-logger >= 0.3.36
- yesod-static >= 1.6.1.0
- esqueleto
# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  back:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - back
